### PR TITLE
Enable creating private packages

### PR DESCRIPTION
**Pull request by gmasclet**
@enys  @davidrapin As discussed, I've forked https://github.com/jsumners/node-activedirectory (which corresponds to the NPM package https://www.npmjs.com/package/activedirectory2)

This pull request adds support for Linkurious private packages creation.

### CODE REVIEW

**Review by enys — CHANGES_REQUESTED** [review]
You have created some files with spaces in the name, could you please remove. See https://github.com/Linkurious/node-activedirectory2/blob/private-packages/%20Jenkinsfile

**Comment by davidrapin** [comment]
@enys wow how did you catch that one?

**Comment by gmasclet** [comment]
@enys good catch! Looks like the bug was located somewhere between the chair and the keyboard. It's fixed :slightly_smiling_face:

**Review by enys — APPROVED** [review]
LGTM, thx

**Pull request merged**
